name: Release Build

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: echo
        run: echo 'work'
        
      - name: Build project
        run: npm install
      
      - name: Build project
        run: npm run build

      - name: Create release archive
        run: |
          mkdir release
          cd release
          zip -r release.zip ../dist
          cd ..