name: Release Build

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - uses: actions/labeler@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Echo-token
        run: echo "${{ secrets.TOKEN_WM }}"

      - name: Build project
        run: npm install
      
      - name: Build project
        run: npm run build

      - name: Create release archive
        run: |
          mkdir release
          cd release
          zip -r release.zip ../dist
          cd ..

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_WM }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION }}
          release_name: 'Release ${{ env.VERSION }}'
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false
      - name: Set Version
        run: |
          echo "VERSION=v$(date +%Y.%m.%d-%H%M%S)" >> $GITHUB_ENV  

      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/release.zip
          asset_name: release.zip
          asset_content_type: application/zip
      - name: Upload release assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: release/release.tar.gz
          asset_name: release.tar.gz
          asset_content_type: application/x-gzip
