name: Build and Release

on:
  push:
    branches:
      - main  # Запускать при пуше в ветку main

jobs:
  echo:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: test
        run: ls -s

          
  release:
    name: Create Release
    permissions:
      contents: write
    needs:
      - echo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: npm install
      - name: Build project
        run: npm run build
      - name: test
        run: ls -s
      - name: Create tar.gz archive
        run: cd dist && tar -czvf ../dist.tar.gz *
      - name: Create zip archive
        run: cd dist && zip -r ../dist.zip * 
      - name: Download 
        uses: actions/download-artifact@v4
        with:
          path: dist.zip
          merge-multiple: true
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: test
          name:  ${{ runner.os }} - v${{ github.run_number }}
          files: |
            dist.zip
            dist.tar.gz
